### ISSUE TITLE
Some browser can't access ws protocol under https

### ISSUE THREAD

**Issue by m5horton** [Aceinna/python-openimu#1]
Example is firefox

**Comment by m5horton** [comment]
This fixes firefox for this issue:
https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue

**Comment by fengliu00** [comment]
The solution for firefox: about:config->click conntinue->network.websocket.allowInsecureFromHTTPS->double click

**Comment by fengliu00** [comment]
Developers.aceinna.com doesn't support Safari.

![safari_web_issue](https://user-images.githubusercontent.com/35041468/43416254-a0ce28c6-93ec-11e8-9e6b-44fbd7cc000b.png)

**Comment by yiweisong** [comment]
I added a solution for Firefox and Safari.
The site will use wss protocol to listen message from python-openimu. And user should implement a websocket server that supports wss.

There is a tool about locally-trusted certificates, it helps to setup local wss server.
https://github.com/FiloSottile/mkcert

**Comment by m5horton** [comment]
Resolved for all except Safari.
