### ISSUE TITLE
Can't display new data file in  "My Files" page

### ISSUE THREAD

**Issue by ysong-aceinna** [Aceinna/python-openimu#10]
After I log a new data file, I can't find it in "My Files" page, despite I reflesh the page for several times. 
I also check "\python-openimu\data" and find the new data file is over there already.

**Comment by ysong-aceinna** [comment]
![issue2](https://user-images.githubusercontent.com/37057411/43318625-0965c9fe-91d4-11e8-9cd6-419cfd1e79e6.png)

**Comment by erkuo521** [comment]
current code can upload your data to ANS, welcome to try.
