### ISSUE TITLE
No warning msg when I run error command "get xxxxx"

### ISSUE THREAD

**Issue by ysong-aceinna** [Aceinna/python-openimu#11]
No warning when I run error command
>>get xxxxx

![issue4](https://user-images.githubusercontent.com/37057411/43317745-a38a16ec-91d0-11e8-98b9-c3a54fa5affb.png)

**Comment by fengliu00** [comment]
Should be fixed in the latest version.

**Comment by erkuo521** [comment]
server.py is recommed to running in future, pls try to used ANS interface side by Chrome.
