### ISSUE TITLE
No response when run command "get orien"

### ISSUE THREAD

**Issue by ysong-aceinna** [Aceinna/python-openimu#12]
![issue5](https://user-images.githubusercontent.com/37057411/43321249-cfe0b3c4-91dd-11e8-99dd-6eaadfff8a1a.png)

**Comment by fengliu00** [comment]
Now, server is running in another thread. Set/get commands works normally when server stops.

**Comment by fengliu00** [comment]
What're packet rate and baud rate? Set baud rate little higher to 115200 for using 100Hz. Try the updated version

**Comment by erkuo521** [comment]
fixed now, we recommend to use serve.py for interface operation on ANS
