### ISSUE TITLE
command "stop" may trigger an error

### ISSUE THREAD

**Issue by ysong-aceinna** [Aceinna/python-openimu#13]
Without run command "record", but run command "stop" directly, it will trigger an error:

![issue6](https://user-images.githubusercontent.com/37057411/43321753-723425c4-91df-11e8-8c5c-87f678fb411b.png)

**Comment by fengliu00** [comment]
Same reason as git #12

**Comment by fengliu00** [comment]
Command stop is not used for stopping server, only for local recording. Please use exit command.

**Comment by erkuo521** [comment]
logic update, fixed now.  we recommend to use server.py for interface operation with ANS.
