### ISSUE TITLE
Meet an error when run command "upgrade "

### ISSUE THREAD

**Issue by ysong-aceinna** [Aceinna/python-openimu#14]
If run command "upgrade " but without any parameter or with wrong parameter, program will crash. Fimware within MCU will be destroyed.
![issue7](https://user-images.githubusercontent.com/37057411/43322753-2fdb3f84-91e2-11e8-92cd-0214e76ee661.png)

**Comment by fengliu00** [comment]
Should be fixed in the latest version.

**Comment by erkuo521** [comment]
fixed now
