### ISSUE TITLE
SyntaxError:invalid syntax

### ISSUE THREAD

**Issue by Linbo2018** [Aceinna/python-openimu#15]
A completely new computer,the first time to install python.

Fail to upload the image, just copy the text 

F:\python-openimu-master\python-openimu-master>pip install azure-storage-blob
Collecting azure-storage-blob
  Downloading https://files.pythonhosted.org/packages/dd/26/45de0cb737aeeeb2fa56cf12ab0042ba64dafd24bcc50bf8c8cdf913a1a6/azure_storage_blob-1.3.1-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 536kB/s
Collecting azure-storage-nspkg>=2.0.0 (from azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/b1/e9/0a11f4feefb9c4c2f7e30d4d448e15b32df3adabe370be70aaf4278fbb52/azure_storage_nspkg-3.0.0-py2.py3-none-any.whl
Collecting azure-common>=1.1.5 (from azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/91/66/6636001c0b6be5423f4bbaffe5febbf9eda39bd1941eb39a73504d8f6f71/azure_common-1.1.14-py2.py3-none-any.whl
Collecting azure-storage-common~=1.3 (from azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/7b/18/03872177864b7ce4aa0302eae5726e8cb66dbb4f30a3408ed27a6639407f/azure_storage_common-1.3.0-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting azure-nspkg>=2.0.0 (from azure-storage-nspkg>=2.0.0->azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/cd/a0/76ca6659ae9afd7567fdbb5b9c85e9c9a0b48238cfcacd92525484408f66/azure_nspkg-2.0.0-py2.py3-none-any.whl
Collecting requests (from azure-storage-common~=1.3->azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.6MB/s
Collecting python-dateutil (from azure-storage-common~=1.3->azure-storage-blob)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 2.1MB/s
Collecting cryptography (from azure-storage-common~=1.3->azure-storage-blob)
  Could not find a version that satisfies the requirement cryptography (from azure-storage-common~=1.3->azure-storage-blob) (from versions: )
No matching distribution found for cryptography (from azure-storage-common~=1.3->azure-storage-blob)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

F:\python-openimu-master\python-openimu-master>python commands.py
Traceback (most recent call last):
  File "commands.py", line 23, in <module>
    from server import WSHandler
  File "F:\python-openimu-master\python-openimu-master\server.py", line 9, in <module>
    from global_vars import imu
  File "F:\python-openimu-master\python-openimu-master\global_vars.py", line 6, in <module>
    from openimu import OpenIMU
  File "F:\python-openimu-master\python-openimu-master\openimu.py", line 515
    except IOError, e:
                  ^
SyntaxError: invalid syntax

F:\python-openimu-master\python-openimu-master>

**Comment by erkuo521** [comment]
i know, for your application. you can run it without python.  only run below newest executable file: 
https://developers.aceinna.com/connect
