### ISSUE TITLE
command: exit then get a error(after server_start)

### ISSUE THREAD

**Issue by blueshu** [Aceinna/python-openimu#17]
![exit](https://user-images.githubusercontent.com/1209509/43395753-cbf10542-9431-11e8-8209-b8265d1162f7.png)

**Comment by fengliu00** [comment]
server_stop works properly on my Win 7. As you mentioned, got a new PC. I guess it should be win10. Let me try to reproduce it on win10.

![server_stop](https://user-images.githubusercontent.com/35041468/43412546-72094322-93e2-11e8-8587-3e687033ee42.png)

**Comment by erkuo521** [comment]
win10 also ok, you can try our executable file, down load link:
https://developers.aceinna.com/connect
