### ISSUE TITLE
Stop command response "Hanging" at prompt

### ISSUE THREAD

**Issue by joem-at-aceinna** [Aceinna/python-openimu#19]
When the "stop" command is sent after recording data, the response "End Collection Task" is left hanging at the command prompt.  Doesn't seem to affect the operation (I can send commands) but it is slightly confusing.

![03_hangingcommanduponstop](https://user-images.githubusercontent.com/35147794/43420994-4c8e6d9e-93fa-11e8-8e75-bcad89c2b71d.PNG)

**Comment by fengliu00** [comment]
fixed

**Comment by joem-at-aceinna** [comment]
Feng made changes to openimu.py and commands.py and resolved the issue.
