### ISSUE TITLE
Python-openimu Ubuntu driver

### ISSUE THREAD

**Issue by FarhadMir** [Aceinna/python-openimu#23]
Neither cloning the python driver from github nor installing through pip works for Ubuntu 16.04; it can search the ports but not connect to any.
![Screenshot from 2019-07-24 17-56-54](https://user-images.githubusercontent.com/36164448/61831688-92762d80-ae3c-11e9-875c-305e0ad4256b.png)

**Comment by yifanff** [comment]
Hi FarhadMir，what is the python version and pip version you are using?  Is the USB interface from IMU mount on the ubuntu system successfully?  what is the ‘lsusb’ command feedback？

**Comment by FarhadMir** [comment]
Hey, Yifan; python 2.7, pip 19.2.1 (but I tried previous versions too); and yes it is succefully mounted look at the screen below:
![Screenshot from 2019-07-25 12-41-09](https://user-images.githubusercontent.com/36164448/61892576-1b8f7200-aeda-11e9-9289-92b7bbb6e790.png)

**Comment by yifanff** [comment]
Hi FarhadMir, thanks for your feedback! please git pull the code and make sure the IMU serial port have full access right, in my side: sudo chmod -R 777 /dev/ttyUSB0 , then it work normally.

**Comment by FarhadMir** [comment]
Thanks, solved.

**Comment by erkuo521** [comment]
at last what is the root cause in your side? based on your situation

**Comment by erkuo521** [comment]
@FarhadMir at last what is the root cause in your side? based on your situation, cable, system not found divice firstly, account access right.......

**Comment by FarhadMir** [comment]
account access right

**Comment by erkuo521** [comment]
so, use command: "sudo usermod -a -G yourusergroup youraccountname" improve the account right will figure out the serial port cannot open problem
