### ISSUE TITLE
data not plotting on web

### ISSUE THREAD

**Issue by m5horton** [Aceinna/python-openimu#24]
I record this via Web interface using OpenIMU300 VG_AHRS Firmware (
OpenIMU300ZA 5020-3885-02 1.1.0 SN:1908400056)

Data is logged
https://navview.blob.core.windows.net/data/data-2019_09_25_12_21_21.csv

But when it plots, shows up blank
![image](https://user-images.githubusercontent.com/5884942/65633176-58d2b780-df90-11e9-944f-f4044dd3596d.png)

**Comment by yiweisong** [comment]
I have fixed the issue in commit https://github.com/Aceinna/ans-frontend/commit/052f2cce37a08aca1e6645d1dc04f1f5bfe6d6f4

Reason
The chart render would use the yAxes from openimu.json>userMessages>outputPackets>graphs, and try to match the header from first line of log file. But the header in first line contains unit for every cell, it won't match any value of yAxes that defined in openimu.json. So there is no plots in chart.

Solution
Extract the header from unit.
