### ISSUE TITLE
Azure blob storage functional update

### ISSUE THREAD

**Issue by sulkytejas** [Aceinna/python-openimu#27]
Azure's latest update has removed AppendBlobService and ContentSettings. 

file_storage.py uses this functions to contact azure blob, if user installs the latest version of azure-blob-storage using pip, the code will break. 

Either the solution is to install older version by `pip install azure-storage-blob==1.4.0` or the better solution is make the necessary structural changes to the file_storage.py.

**Comment by m5horton** [comment]
Need to get this closed ...
