### ISSUE TITLE
Python driver usage

### ISSUE THREAD

**Issue by matteocutugno** [Aceinna/python-openimu#35]
Hello,
i'm new to python so maybe this is a trivial question. 

Referring to manual page https://openimu.readthedocs.io/en/latest/tools/python.html 
it says that " The Python driver reads a JSON file by default named openimu.json to understand the messages - both primary output packets, as well as command/response type packets from the IMU. These can be customized by changing the JSON file and the Python script will use that information to parse data (literally the byte stream) from the OpenIMU in real-time appropriately. Here are a few samples function you can call with the driver."

I didn't understand how to interact with python driver.  I have to write a new .json file?  Or i have to modify the openimu.json file already in the example ins application? How can i do it?

Thanks

Matteo

**Comment by m5horton** [comment]
This kind of question is better asked on https://forum.aceinna.com

The quick answer is you only need to modify .json file **IF** and **WHEN** you are adding new packets or new commands to the embedded firmware.  This lets the Web GUI on https://developers.aceinna.com know that new commands and packets are available, and then display them properly in the GUI.
