### ISSUE TITLE
Openrtk330 cannot display data on OpenRTK Monitor

### ISSUE THREAD

**Issue by SwingW** [Aceinna/python-openimu#39]
![1](https://user-images.githubusercontent.com/45917104/80858657-51456080-8c8d-11ea-8492-f7212fd7d3a7.png)
Errors in running ans-de'vices
![2](https://user-images.githubusercontent.com/45917104/80858679-67532100-8c8d-11ea-8ef9-35ff46779d85.png)

**Comment by yiweisong** [comment]
It looks like the device is sending an empty packet.
1. Which version of driver are you using? Develop branch or an executor ?
2. Does it still happen after restart the driver?

**Comment by SwingW** [comment]
![1](https://user-images.githubusercontent.com/45917104/81146916-d1303b00-8fab-11ea-8076-dc9e957f978a.png)
Yes, restarting the program still does not work

**Comment by yiweisong** [comment]
It seems your device is not the latest version. Could you contact the person who sell the device to you?

**Comment by SwingW** [comment]
I don't quite understand what it means that the device is not the latest version? Do I need to update the firmware

**Comment by SwingW** [comment]
I don't quite understand what it means that the device is not the latest version? Do I need to update the firmware

**Comment by SwingW** [comment]
I don't quite understand what it means that the device is not the latest version? How should I see the version of openrtk330

**Comment by SwingW** [comment]
I don't quite understand what it means that the device is not the latest version? How should I see the version of openrtk330Li and how can i solve this problem

**Comment by dw-gnss-aceinna** [comment]
@SwingW we had a firmware upgrade to a new architecture, please share us with ur email address  if it's ok, we can share you steps to upgrade your device first.

**Comment by SwingW** [comment]
Ok, my mailbox is: 2460613245@qq.com,thank you

**Comment by dw-gnss-aceinna** [comment]
email sent, any more questions let us know,

**Comment by SwingW** [comment]
Hello, I followed the tutorial to update the firmware, and it also shows that the update was successful, why is my firmware version still 1.0.7
![1](https://user-images.githubusercontent.com/45917104/81253584-80781b00-905b-11ea-9a95-4f6a221e58d7.png)
![2](https://user-images.githubusercontent.com/45917104/81253627-94bc1800-905b-11ea-9e11-8492e3e010ff.png)

**Comment by dw-gnss-aceinna** [comment]
firmware version is 1.0.7, correct, and the RTK_INS App is v1.2.2.

**Comment by SwingW** [comment]
Yes, but no data is generated in the openrtk or openimu Monitor window, do you know what caused this situation?
![3](https://user-images.githubusercontent.com/45917104/81256951-8faf9680-9064-11ea-9b8b-9d5a564a4c6b.png)

**Comment by dw-gnss-aceinna** [comment]
pls refer to online doc https://openrtk.readthedocs.io/en/latest/useOpenRTK.html for how-to-use

**Comment by SwingW** [comment]
> 请参考在线文档https://openrtk.readthedocs.io/en/latest/useOpenRTK.html，了解如何使用

Hello, I am operating according to the online documentation tutorial, but I still have not received the gnss signal and imu data, and the open rtk330EVB does not blink when the power is connected to the yellow LED and the green LED. I want to ask you know what is the reason for this Is it

**Comment by dw-gnss-aceinna** [comment]
Did u upgraded the firmware I sent u in the email? Or could you share us your WeChat, our engineer will help with it.

Best,

Da




On May 10, 2020, at 17:35, SwingW <notifications@github.com<mailto:notifications@github.com>> wrote:



请参考在线文档https://openrtk.readthedocs.io/en/latest/useOpenRTK.html，了解如何使用<https://openrtk.readthedocs.io/en/latest/useOpenRTK.html%EF%BC%8C%E4%BA%86%E8%A7%A3%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8>

Hello, I am operating according to the online documentation tutorial, but I still have not received the gnss signal and imu data, and the open rtk330EVB does not blink when the power is connected to the yellow LED and the green LED. I want to ask you know what is the reason for this Is it

**Comment by SwingW** [comment]
My WeChat account is：18859275931，thank you for your help
