### ISSUE TITLE
OpenIMU Connected, but Website says discconnected

### ISSUE THREAD

**Issue by kevindean** [Aceinna/python-openimu#40]
Hello again,

I have to IMU connected to the port, however, the website says that the imu is not connnected. Advice? Thank you.

![Screenshot from 2020-05-11 12-45-46](https://user-images.githubusercontent.com/1910120/81587857-9ea88880-9385-11ea-8b74-bf5e43356f4c.png)

**Comment by yifanff** [comment]
Hi, switch to chrome browser and refresh the develper page,please have a try.

**Comment by kevindean** [comment]
Sounds good, I will give that a go and let you know the results. Thank you.

-Kevin

**Comment by baweiji** [comment]
The web has a retry policy, if the web cannot detect the device in 50 times try, it will refuse to detect. You can try one of below actions,
1. Please refresh the page, and try it again. 
2. Click the chain icon on the right top of the page, then click the refresh button to detect device again.
