### ISSUE TITLE
bootstrap/cli -- NameError: name 'x' is not defined  

### ISSUE THREAD

**Issue by jgladen** [Aceinna/python-openimu#41]
Error triggered by setting option using cli interface

```
>>set gps_protocal
Usage: set gps_protocal <values>
values:
[{'key': '0', 'value': 'UBLOX_BINARY'}, {'key': '1', 'value': 'NOVATEL_BINARY'}, {'key': '3', 'value': 'NMEA_TEXT'}]
>>set gps_protocal 1
.
.
.
... packages\aceinna\bootstrap\cli.py", line 222, in set_handler
    (select_param['type'] == "int64" and int(self.input_string[2]) not in x['options'])):
NameError: name 'x' is not defined
```

**Comment by yiweisong** [comment]
Thanks for your feedback.

We have fixed the issue in develop branch. In commit [1f2a96e0ff52670691b995e0378d879629a0a567](https://github.com/Aceinna/python-openimu/commit/1f2a96e0ff52670691b995e0378d879629a0a567)

And we will also include this fix in next release.
