### ISSUE TITLE
conflict in record between WS version and CLI 

### ISSUE THREAD

**Issue by m5horton** [Aceinna/python-openimu#5]
If CLI is in WS server mode, then record command fails due to lack of user.   Nice to handle both case more elegantly.

![image](https://user-images.githubusercontent.com/5884942/43214462-26ee0a14-8fee-11e8-893c-f92be52b5d37.png)

**Comment by fengliu00** [comment]
Not able to support concurrently recording on both web and cli now.

**Comment by m5horton** [comment]
CLI deprecated
