### ISSUE TITLE
How to change nmea data log frequency in web or pythondriver-win?

### ISSUE THREAD

**Issue by fei4xu** [Aceinna/python-openimu#71]
Hi,

I'm using the downloaded pythondriver-win.zip from https://github.com/Aceinna/python-openimu/releases/tag/v2.5.2ict

It's working fine and all the yellow/green/red leds are flashing during the data logging.
I also used the tool with `parse` subcommand to parse the saved .bin into nmea log.

but I'd like to check how to change the nmea data log frequency? I have PC/web based configuration like this:
![image](https://user-images.githubusercontent.com/46098686/129919823-0816a518-e101-420b-b2d8-06476a4e99cf.png)
which parameter should I change?

I also have the Android tool, there's a clear setting page to change that value, can I use android tool for nmea freqency and then use PC pythondriver-win to log data?

**Comment by yiweisong** [comment]
Firstly, please don't use the release with version v2.5.2ict, it is for specified user. It is better to use this one https://github.com/Aceinna/python-openimu/releases/tag/v2.5.0

**Comment by yiweisong** [comment]
We don't supply nmea log frequency configuration now.

**Comment by fei4xu** [comment]
![Screenshot_20210819-145236_OpenRTK](https://user-images.githubusercontent.com/46098686/130543445-152feabd-99dd-4f42-901d-4ddb1c9ce39e.jpg)
This is the screenshot I took from the Android BLE App, on which `UserPacketRate` is configurable and the value is 100.
Can I use the Android App to configure it?

**Comment by yiweisong** [comment]
I think so, you can try. The packet rate options you could refer to the RAWIMU in the web page.
