### ISSUE TITLE
error message when run "ans-devices.exe parse -p ....."

### ISSUE THREAD

**Issue by fei4xu** [Aceinna/python-openimu#72]
HI,

I tried to get nmea data in csv format so I run:
```
ans-devices.exe parse -p ....
```
there were lots of error message like:
```
error happened when decode the s1 pack expected 36 items for packing (got 30)
error happened when decode the s1 pack expected 36 items for packing (got 30)
error happened when decode the s1 pack expected 36 items for packing (got 30)
error happened when decode the s1 pack expected 36 items for packing (got 30)
error happened when decode the s1 pack expected 36 items for packing (got 30)
Parse done.
```
but in the end I can get the parsed output file of `user_2021_09_09_15_54_16-nmea`.

What does the error message mean?

**Comment by yiweisong** [comment]
It seems you are using an old version of setting file. It affects packets data parse, such as s1, o1, i1 etc. If you just need the nmea data, please ignore it.

To refresh the setting file, please try to delete the folder named `OpenRTK330L`, `RTK330L` and run the application again. If it still output the message, checkout to develop branch, and copy the setting files from `/src/aceinna/setting` to `/your executor path/setting`.
