### ISSUE TITLE
Error message when I run "openimu parse"

### ISSUE THREAD

**Issue by k2ironman** [Aceinna/python-openimu#77]
I installed the driver with pip and tried to get data form OpenRTK330 with the `openimu parse` command, get the following output:
```
[Info] Python driver version: 2.6.0
Application Exit Exception: /home/pi/openimu/libs/UserDecoderLib_linux.so: cannot open shared object file: No such file or directory
```
I checked and the file exists.
What could cause this error?

**Comment by yiweisong** [comment]
There are some parameters miss.

Please try `openimu parse -p {folder path}`. The fold path is the container folder of log files.
